"""initial schema

Revision ID: 3e2b65f3bf2a
Revises: 
Create Date: 2026-09-04 14:15:58.240111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2b65f3bf2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('party_type', sa.String(length=100), nullable=True),
    sa.Column('contact_info', sa.String(length=300), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_serialized', sa.Boolean(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('unit_label', sa.String(length=50), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('IN_STOCK', 'OUT', 'MAINTENANCE', 'LOST', 'RETIRED', name='unitstatus'), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('kit_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_item_type_id', sa.Integer(), nullable=False),
    sa.Column('accessory_item_type_id', sa.Integer(), nullable=False),
    sa.Column('default_quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['accessory_item_type_id'], ['item_type.id'], ),
    sa.ForeignKeyConstraint(['parent_item_type_id'], ['item_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_item_type_id', 'accessory_item_type_id')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_member_id', sa.Integer(), nullable=False),
    sa.Column('is_for_self', sa.Boolean(), nullable=False),
    sa.Column('holder_contact_id', sa.Integer(), nullable=True),
    sa.Column('checkout_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('returned_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PARTIALLY_RETURNED', 'RETURNED', 'CANCELLED', name='loanstatus'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_member_id'], ['team_member.id'], ),
    sa.ForeignKeyConstraint(['holder_contact_id'], ['party_contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('item_unit_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_returned', sa.Integer(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('line_status', sa.Enum('ACTIVE', 'PARTIAL', 'RETURNED', 'LOST', 'DAMAGED', name='loanlinestatus'), nullable=False),
    sa.Column('is_from_kit', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ),
    sa.ForeignKeyConstraint(['item_unit_id'], ['item_unit.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_line')
    op.drop_table('loan')
    op.drop_table('kit_component')
    op.drop_table('item_unit')
    op.drop_table('party_contact')
    op.drop_table('item_type')
    op.drop_table('team_member')
    op.drop_table('party')
    op.drop_table('category')
    # ### end Alembic commands ###
