"""remove email and phone from team_member

Revision ID: d3ee0ddc0456
Revises: d14df46e21ba
Create Date: 2026-09-04 14:02:50.449145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ee0ddc0456'
down_revision: Union[str, Sequence[str], None] = 'd14df46e21ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
